### PR TITLE
Fix rdf_prefix_path to work for 3.0.0

### PR DESCRIPTION
**Pull request by white-gecko**
Example to fix the issue pointed out in #56.

### CODE REVIEW

**Comment by white-gecko** [comment]
This must be something very strange.

**Comment by RohanAsmat** [comment]
Now it seems to be an error on frontend side! @white-gecko right?

**Comment by white-gecko** [comment]
@RohanAsmat Are you able to locate the error?

**Comment by RohanAsmat** [comment]
According to the log following query is the reason:
`
 Query: 
          # select all main Navigation position properties for counting
          SELECT ?position WHERE{
              sdatech:Mainnav ?positionProp ?resource .
              ?positionProp a rdfs:ContainerMembershipProperty .
              ?positionProp rdfs:label ?position .
          }
           
`

That for the header definition, which is true the build goes fine without including source for header definition. But, for this we didn't changed structure of the turtle file neither code  and it is surprising that it stops working!

**Comment by white-gecko** [comment]
Could you fix the problems?

**Pull request merged**
